### ISSUE TITLE
User unable to import follow list

### ISSUE THREAD

**Issue by CanuteTheGreat** [CanuteTheGreat/madscientists#2]
error reported is "has contents that are not what they are reported to be" - see https://madscientists.social/@greygoo/110664152995101128

**Comment by Vault2501** [comment]
![Screenshot_20230708_212237](https://github.com/CanuteTheGreat/madscientists/assets/109519373/8502485d-2704-4f5b-8293-e4e82f7dab37)

Fixed as well!
