### ISSUE TITLE
Image are not displayed anymore in the time line.

### ISSUE THREAD

**Issue by Vault2501** [CanuteTheGreat/madscientists#4]
This might be related to
[ ] https://github.com/CanuteTheGreat/madscientists/issues/3

Description:

When browsing the timeline, posted images are blurred and not displayed correctly anymore. When clicking on them, the images get opened fine in a new tab. see attached screenshot.

![Screenshot_20230708_202721](https://github.com/CanuteTheGreat/madscientists/assets/109519373/15f8f31e-de3f-496f-a474-d04d3ad48f31)

**Comment by CanuteTheGreat** [comment]
Seems to have shown up at the same time as the update to 4.1.3

**Comment by Vault2501** [comment]
https://github.com/mastodon/mastodon/issues/25776 yes

**Comment by CanuteTheGreat** [comment]
Issue was imagemagick. Built a newer version and that seems to have resolved multiple issues including this one.
